### ISSUE TITLE
比 BA 那个写的好

### ISSUE THREAD

**Issue by Easyzhan** [qingweiiOS/QWTabBar#1]
那个的 pushhiden 没有管理好

**Comment by qingweiiOS** [comment]
pushhidden 我一般在 navigationController 管理的！

**Comment by Easyzhan** [comment]
![](https://ws3.sinaimg.cn/large/006tNc79gy1fvq3y1imkcj30oi048ta3.jpg)
ipad 上有问题啊兄弟

**Comment by Easyzhan** [comment]
ipad 设置只支持竖屏，在启动的时候横着放 ipad 也会出现错乱

**Comment by Easyzhan** [comment]
UIInterfaceOrientation orientation = [UIApplication sharedApplication].statusBarOrientation;
    if (orientation == UIInterfaceOrientationPortrait || orientation == UIInterfaceOrientationPortraitUpsideDown) {
        tempW = K_WIDTH_QW;
        NSLog(@"---竖着-");
    }else {
        NSLog(@"---横着-");
        tempW = WINDOW_HEIGHT;

    }
处理了，我的办法目前是这样，作者如果有更好的告诉我一下哈

**Comment by qingweiiOS** [comment]
四川的还是重庆的😄

**Comment by qingweiiOS** [comment]
更新了新版本，可以去试用一下
